import os

from dotenv import load_dotenv


load_dotenv()

SYSTEM_PROMPT_FILE = os.getenv("SYSTEM_PROMPT_FILE")
ROUTER_CLASSIFICATION_PROMPT = os.getenv("ROUTER_CLASSIFICATION_PROMPT")
SEARCH_AGENT_PROMPT = os.getenv("SEARCH_AGENT_PROMPT")
TRANSCRIPTION_AGENT_PROMPT = os.getenv("TRANSCRIPTION_AGENT_PROMPT")
ROUTER_SYNTHESIS_PROMPT = os.getenv("ROUTER_SYNTHESIS_PROMPT")

SERPAPI_API_KEY = os.getenv("SERPAPI_API_KEY")

FETCH_SITE_BASE_URL = os.getenv("FETCH_SITE_BASE_URL").rstrip("/")
FETCH_SITE_BEARER_TOKEN = os.getenv("FETCH_SITE_BEARER_TOKEN")
FETCH_SITE_SUBMIT_URL = os.getenv(
    "FETCH_SITE_SUBMIT_URL",
    f"{FETCH_SITE_BASE_URL}/document_to_markdown",
)
FETCH_SITE_STATUS_URL_TEMPLATE = os.getenv(
    "FETCH_SITE_STATUS_URL_TEMPLATE",
    f"{FETCH_SITE_BASE_URL}/status/{{task_id}}",
)
FETCH_SITE_TIMEOUT_SECONDS = float(os.getenv("FETCH_SITE_TIMEOUT_SECONDS"))
FETCH_SITE_POLL_INTERVAL_SECONDS = float(
    os.getenv("FETCH_SITE_POLL_INTERVAL_SECONDS")
)
